name: dotnet-sopi-devops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:        
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore dirs.proj -v m --nologo

    - name: Build
      run: dotnet build dirs.proj --configuration Release -v m --nologo --no-restore
 
    - name: Test
      run: dotnet test dirs.proj --configuration Release --no-build --logger:trx --no-build --no-restore
      
    - name: Pack
      run: dotnet pack dirs.proj --configuration Release -v m --nologo --no-restore --output artifacts

    # - name: push package
    #   run: dotnet nuget push "*.nupkg" -k $NUGET_API_KEY
    #   working-directory: dotnet-sopi-devops/SoftwarePioniere.DevOps/nupkg

